// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtBLjAuBPGVrzPchRaCU5xfJmn5oUc2SM',
    appId: '1:662618502573:web:de5615399a519e7fde1d24',
    messagingSenderId: '662618502573',
    projectId: 'e-commerce-app-74deb',
    authDomain: 'e-commerce-app-74deb.firebaseapp.com',
    storageBucket: 'e-commerce-app-74deb.appspot.com',
    measurementId: 'G-SCSR9C925B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPDw2gjM4Ww4_3GtxA2RmI47ijRGLI0Cc',
    appId: '1:662618502573:android:afb67ed0bae0fd64de1d24',
    messagingSenderId: '662618502573',
    projectId: 'e-commerce-app-74deb',
    storageBucket: 'e-commerce-app-74deb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJDztLwYvXRvCSPvhEF8_il8B0YRkUb_I',
    appId: '1:662618502573:ios:34d251e5dec0f933de1d24',
    messagingSenderId: '662618502573',
    projectId: 'e-commerce-app-74deb',
    storageBucket: 'e-commerce-app-74deb.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJDztLwYvXRvCSPvhEF8_il8B0YRkUb_I',
    appId: '1:662618502573:ios:34d251e5dec0f933de1d24',
    messagingSenderId: '662618502573',
    projectId: 'e-commerce-app-74deb',
    storageBucket: 'e-commerce-app-74deb.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtBLjAuBPGVrzPchRaCU5xfJmn5oUc2SM',
    appId: '1:662618502573:web:7d1a4a92bfe7919dde1d24',
    messagingSenderId: '662618502573',
    projectId: 'e-commerce-app-74deb',
    authDomain: 'e-commerce-app-74deb.firebaseapp.com',
    storageBucket: 'e-commerce-app-74deb.appspot.com',
    measurementId: 'G-S3NJZDVC7K',
  );
}
